### ISSUE TITLE
"Show Avatar" is not saved to options file

### ISSUE THREAD

**Issue by Chris-WF** [3vi1/IMP#11]
In e.g. `Options.:loadSettings()` the option to show/hide avatar is beeing considered:
```c++
ui->checkAvatar->setChecked(settings.value("showAvatar", true).toBool());
```

However in `Options::saveSettings()` it's missing.
The line to be added I believe should be:
```c++
settings.setValue("showAvatar", _showAvatar);
```

or if you want to add a `Options::getShowAvatar()` method first:
```c++
settings.setValue("showAvatar", getShowAvatar());
```

**Comment by Chris-WF** [comment]
Workaround

- Open: `C:\Users\<USERNAME>\AppData\Local\EternalDusk\IMP\imp-settings`
- Add line: `showAvatar=false`

**Comment by 3vi1** [comment]
Thanks for the report.  I've corrected it in my local source and will push it up when I do this weeks release sometime in the next few days.
