### ISSUE TITLE
Avatars not loading

### ISSUE THREAD

**Issue by tenowg** [3vi1/IMP#15]
When I have the setting for "show avatars" all I get is the default IMP icon in chat messages.

![noavatar](https://cloud.githubusercontent.com/assets/1147426/26222904/c3de219c-3be9-11e7-86c8-2f37de8e5767.PNG)

System is Windows 10, also I have never got any avatars to show.

**Comment by tenowg** [comment]
seems this is fixed, just need to wait for new download for missing dll's

**Comment by 3vi1** [comment]
Fixed.  Thanks for the report.
