### ISSUE TITLE
First two menu items "Pilots Find" not accessable

### ISSUE THREAD

**Issue by tenowg** [3vi1/IMP#16]
The first two menu items "Pilots" and "Find" in the main menu are not accessible by mouse hover. They do dropdown if I have any other menu open and then drag to them.

System is Windows 10, this is a fairly new issue for me.

**Comment by tradari** [comment]
Also confirm this issue with windows 10

**Comment by 3vi1** [comment]
This should be fixed in the current release I put out yesterday.  Turns out an invisible widget was overlapping the menus on Windows.  Thanks for the heads-up!
