### ISSUE TITLE
All Messages menu item is hidden in main menu

### ISSUE THREAD

**Issue by tenowg** [3vi1/IMP#17]
I found this issue after undocking the message pane, and after reloading IMP, the message pane was gone. 
Nah Col was good enough to let me know that if you right clicked the main menu with nothing open, a menu with "All Messages" option would show, fixing this issue.

**Comment by 3vi1** [comment]
The 'L' key will hide/show the messages pane if you ever lose it.  Make sure to click the IMP window first so that it gets the keypress.

I'll add a right-click menu over the map in the near future so that it's more obvious how to get these things back, especially when in overlay mode.
