### ISSUE TITLE
cant reanable chat log showing

### ISSUE THREAD

**Issue by NormannK** [3vi1/IMP#19]
somehow i disabled the chat log on the left site. But i cant find a way to enable it again.
Nor I can find a config file or something similar the change settings.
Thanks

**Comment by RedDevilGiant** [comment]
myself and a number of my corpmates have stumbled upon this same problem.

**Comment by NormannK** [comment]
found it:
L: Toggle on/off Message List.

**Comment by RedDevilGiant** [comment]
thank you, maybe its an idea to add it to the list under the "window" menu?

**Comment by 3vi1** [comment]
Had a guy ask me about this today.  I'll leave this open until I add a menu option (probably in 0.9.4).

**Comment by 3vi1** [comment]
Menu option added ~0.9.4.2
