### ISSUE TITLE
Color the recognized systems and make them clickable

### ISSUE THREAD

**Issue by Bazzek** [3vi1/IMP#2]
One of the nice things in Vintel is that you can click the system name in a message that scrolls by to see where it is, on top of that the system is colored instead of standard arial.

Would it be possible to add this feature some time in the future?

**Comment by 3vi1** [comment]
Yes.  The message view has been low on my priority list until recently, because I usually have it closed myself.  But, I can add this in the near future.

I'll leave this open until I get it in IMP.

**Comment by 3vi1** [comment]
In v0.8.0 I've added colorization to the message view.  In addition: systems, ships and other keywords get colorized.  Double-clicking the message will activate the find feature for the system.
