### ISSUE TITLE
I am in multiple locations

### ISSUE THREAD

**Issue by ppfeufer** [3vi1/IMP#21]
» 1 client online
» IMP started after the client
» shows I am in 3 different locations
» deactivating pilots from the "Pilots" menu doesn't do anything

![screenie_192](https://user-images.githubusercontent.com/2989985/27166927-32bd62fc-519e-11e7-96e0-51898391378c.png)

**Comment by 3vi1** [comment]
Is this fixed for you in the current version?  I think I may have corrected one issue that causes this around 0.9.4.2.

**Comment by ppfeufer** [comment]
As far as I can tell, deselecting pilots now works and also removed the ghosts location.

Thanks.

**Comment by 3vi1** [comment]
Great!  Thanks for the report!
