### ISSUE TITLE
Jump Bridge Data

### ISSUE THREAD

**Issue by mossyblog** [3vi1/IMP#23]
If you point at Dotlan URL it wont download (as i'm assuming it needs a specific file)

Also what kind of file data structure is it looking for?

**Comment by 3vi1** [comment]
Correct, it uses it's own format of "1st-sys=2nd-sys:#color".  ex:

3D-CQU=9UY4-H:#0F00FF
3KB-J0=AY-YCU:#804030
49GC-R=8B-VLX:#1F00EF
5KG-PY=QBL-BV:#2F00DF
...

The files should be named the same as the system, but all lowercase (ex.:  "providence").
