### ISSUE TITLE
No Sounds Play and Messages Not Pulled from Intel

### ISSUE THREAD

**Issue by PhilidusRenn** [3vi1/IMP#28]
So I just updated the app and the program does not pull fresh intel from the channels when it is posted nor does it play any of the alert sounds when a red is reported within any of my designated proximities.

**Comment by PhilidusRenn** [comment]
There is also a long delay in the application pulling fresh intel or sometimes it doesn't pull at all. I'm not sure what the problem is. I have tried messing with the settings for the poller and making sure I have all the proper channels included in the settings to pull from, however, the tool is simply not performing like it did a few weeks back.

**Comment by 3vi1** [comment]
Had someone else report similar problems on Windows.  I reverted the update flag and will take a look at this soon.

**Comment by Lemoncress** [comment]
seems the fallbackpoller wasn't running under windows.
I had to put
```
#ifdef Q_OS_WIN32 // Q_OS_LINUX
#define USE_FALLBACK_POLLER
#endif
```
below the include section of logcatcher.cpp rather than the header, then it started to work. 

(I'm a hobbyist so I only understand about 70% of what I'm doing)

**Comment by 3vi1** [comment]
Interesting; thanks for the info.

This weekend I should have some time to sit down at a Windows machine (I don't have it on any of my own systems - I compile the exe in a VM that can't run Eve itself) and take a look at the issue.  I'll put together a new release as soon as I've fixed/tested it.

**Comment by tradari** [comment]
I can confirm i have this issue on windows 10 also
