### ISSUE TITLE
Only 1 Character showing up

### ISSUE THREAD

**Issue by ZefixDangit** [3vi1/IMP#3]
Hey there, 

my problem is that only 1 of my characters are showing up in the menu, but playing with 2 at the same time.
Is there a workaround or do i have to add the other somehow?

Greetings, Zefix

**Comment by 3vi1** [comment]
If this is still an issue in the current version, please let me know.  Until the last month or so, I've not played 2 characters at once.  But... it appears to be working now - so hopefully I fixed your issue in the meantime?

If not, let me know, as I'm finally in a good position to test.
