### ISSUE TITLE
See-trough

### ISSUE THREAD

**Issue by HendrikPetertje** [3vi1/IMP#31]
My imp screen became see-trough all of a sudden. Toggling overlay mode, always on top and other options doesn't seem to fix the issue. It seems there are no menus in place to make imp normal again.

Screenshot below as a sample:
![screenshot_1](https://user-images.githubusercontent.com/3583395/30511772-2e21f010-9ae0-11e7-9076-04878b9eae2b.png)

Am overlooking something, or did something go wrong?

**Comment by 3vi1** [comment]
I think you accidentally discovered the Ctrl + Alt + Mousewheel shortcut to adjust the window transparency.

Try that and see if it makes it solid again.

**Comment by HendrikPetertje** [comment]
I'm sorry, yes. That seems to fix all issues!

**Comment by 3vi1** [comment]
Great!
