### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Bafugly** [3vi1/IMP#42]
Not sure if this is an Imp issue or not.   But my download of the current version is stuck in transparent mode.  ?    

How to make it not be transparent.?

**Comment by 3vi1** [comment]
You've probably accidentally adjusted the window transparency:  Ctrl+Alt+Mousewheel.

**Comment by Bafugly** [comment]
Oh snap.    Thats exactly what it is.....Thankyou 

Amazing tool by the way.

**Comment by ChefTom** [comment]
Hi
I play EvE on a laptop without a mouse wheel...
How can I change transparency mode?

**Comment by 3vi1** [comment]
^ How do you do any mouse wheel operation on your laptop?  If you can, then use that.

I'll add other ways to modify transparency via menus in future versions.
