### ISSUE TITLE
Feature Request: Link Avatar to zKillboard

### ISSUE THREAD

**Issue by cyberrodent** [3vi1/IMP#46]
Its great that the message shows the toon's avatar.  I would love to be able to click on the avatar (or some new icon) to spawn a browser window with that toons zkillboard.

Thank you for a wonder bit of software.

**Comment by 3vi1** [comment]
Hmmm... The users for whom you'd see icons are generally blue people reporting in your intel channels.... But, they might be reporting red fleets that killed them... so...  It doesn't sound like a bad idea.  I'm adding it to the short list of to-do's.
