### ISSUE TITLE
Jump Bridge Data

### ISSUE THREAD

**Issue by ghost** [3vi1/IMP#47]
would it be possible to have imp to use .txt files for jb data as these change from region to region

**Comment by 3vi1** [comment]
It already does.  :)

Imp uses text files for jump bridge data.  By default, they're hosted on my site.... and probably out of date  :)

BUT... you can direct it to your own local file.  For instance, if you set your Settings | Options | Map | Bridge Data to "file:///home/evil/Documents/imp_testing/" (this is on Linux, change the file: path for Windows), you can create a file called "providence" in it and it will control the providence jump bridges.

**Comment by Velkyn-Elamshin** [comment]
I'm having a heckuva time trying to get custom jump bridge file to show up, perhaps you can tell me what I'm doing wrong?

path:
file:///C:\Users\arkon\Documents\EVE\imp\jumpbridges/

custom map file:
great_wildlands.txt

test jump bridge:
8DL-CP=0-3VW8:#0F00FF

For the path I've tried forward slashes, backslashes, " " quotations, so far nothing is showing up. If IMP is reading the file, I'm not getting any links between systems to "show" a jump bridge connection.

Your help on this is greatly appreciated.
