### ISSUE TITLE
New log file names

### ISSUE THREAD

**Issue by ppfeufer** [3vi1/IMP#48]
Since yesterdays patch, CCP introduced a new messed up way to name the chat log files, IMP doesn't recognize them anymore ...

**Comment by 3vi1** [comment]
Yes, heard this from another player an hour or so ago.  Will fix after work ASAP.

**Comment by 3vi1** [comment]
Should be fixed now.  :)  https://github.com/3vi1/IMP/releases/tag/v0.9.7.3

**Comment by ppfeufer** [comment]
Nope, still not working here :-(
