### ISSUE TITLE
Intel Chat Still Not working

### ISSUE THREAD

**Issue by Pocketfrog** [3vi1/IMP#49]
I updated to the most recent v0.9.7.3 due to the bug that stopped intl from the channels reaching imp. but its still broken. No RED ALERT! 

I wish there was a way to test it without doing a test in the intl channel, they going to be yelling at me soon for sticking TEST in there every now and again. They think TEST alliance is attacking :|

**Comment by Pocketfrog** [comment]
AHHH Its working now. Here's what I did. After I tried installing and reinstalling imp and restarting eve several times, I left the intl chat channel completely and rejoined and then suddenly imp started gathering the messages and that nice safe feeling you get from the RED ALERT!! warning returned. 

So all is well, RED ALERT!!! is back!

**Comment by 3vi1** [comment]
> I wish there was a way to test it without doing a test in the intl channel

In the Settings | Options | Messages (tab), you can add any channel as an intel channel.  You can add your own personal channel there if you want to test rules without having it affect others.  :)

Someone else mentioned a similar experience (having to rejoin channels).  I'm pretty sure there's something still wrong here.  In quick testing just now I see that, for some reason, EVE is creating some channel logs in the old format (like when you rejoin), but not always.  I'll look into this further today.

**Comment by 3vi1** [comment]
Yep.  Found the problem on the commute into work.  Apparently I missed one other place in the code where the length of the non-channel portion of the filename was assumed.  I'll see if I can patch it at lunch and upload a new pre-release.

Thanks for the heads-up.

**Comment by GabrielenT** [comment]
On the newest 0.9.7.4 vesrion the issue still persists, but after i rejoined the channel it works

**Comment by ppfeufer** [comment]
Yep, still not working properly. Some channels work, others don't.

**Comment by 3vi1** [comment]
Found the problem - yet *another* place where I assumed the old naming format instead of regex'ing.  I'll fix it today, right after I'm done with some real-life work.

**Comment by 3vi1** [comment]
Put up a v0.9.7.5 pre-release that should fix it.  I consolidated some code so this won't be as painful the next time CCP decides to add bugs to the logging.  Will test more tonight before setting the update notification and closing this issue.

I'm still not sure how they broke their logic such that it only *sometimes* adds the number of channel members to the log name.  But after messing up the fix with hurried releases, I don't have any room to talk.  :)

**Comment by 3vi1** [comment]
Well this is interesting....

```
2018.03.25 12:07:17> LogCatcher::findCurrentLogs - Watching  "/home/evil/Documents/EVE/logs/Chatlogs/N-RMSH Chat_20180324_192135.txt"  =  true
2018.03.25 12:07:17> LogCatcher::findCurrentLogs - Watching  "/home/evil/Documents/EVE/logs/Chatlogs/North Provi Intel [98]_20180325_120716.txt"  =  false
```

Apparently, even though I'm trying to watch the correct logs, QFileSystemWatcher::addPath is failing randomly.  Will have to investigate this further.

**Comment by Pocketfrog** [comment]
seems to be working ok for me
