### ISSUE TITLE
restore windowed mode

### ISSUE THREAD

**Issue by Port66** [3vi1/IMP#52]
Love the program, simple interface allowing for so much, thanks.   I misclicked and maximized the window in windows 10, How do I restore it or show normal again?

**Comment by 3vi1** [comment]
I'm guessing it's maximized and in frameless mode?  Click any empty space on the map to make sure it's selected, then press the 'w' key to toggle framless mode back off.

**Comment by Port66** [comment]
It is not in Frameless, but that worked. I could still see the menu. has to be a windows 10 fail to understand what to do with the app. Thanks it is much better.
