### ISSUE TITLE
Request - Additional notification

### ISSUE THREAD

**Issue by titch98** [3vi1/IMP#7]
Hi. Recently started using after the news about Vintel and so far, looks a very good Intel aid.

The only thing I would like to see to make the experience better during play, is the option to set more than one Alarm Distance notifications. Personally, I would like to set '0', '1' and '2' jumps out. This is a feature found (although by default) in Near2 that I like very much, as there is much more advanced warning on what is happening around you, and as I am using voice audio in IMP as warnings, gives me a much clearer indication on who is around.

Keep up the great work and thank you for your time and effort on this project :)

**Comment by 3vi1** [comment]
Love the idea.  In a future version, I'll add a dynamic list where you can set different sounds (and volumes) to correspond to the number of jumps to the alert.

I was already going to add an option that let you set an amount of sound dropoff per system away, but being able to have "Reds 2 jumps out" or "Reds 3 jumps away" alerts is even more useful.

**Comment by Chris-Devine** [comment]
Yer would be good if you could hook into some text to speech type libary

**Comment by 3vi1** [comment]
I've added this functionality in 0.9.3.

Text to speech will be coming in one of the next few releases.

**Comment by titch98** [comment]
[sound files.zip](https://github.com/3vi1/IMP/files/1209711/sound.files.zip)
Nice to see the implemented Alarm Distance feature. I have loaded my own audio files into IMP Audio File that makes the experience much better. These were created through TTS software and converted to WAV for use. I have attached them in a zip file and maybe something you may consider as part of your next release?

**Comment by titch98** [comment]
[status_request.zip](https://github.com/3vi1/IMP/files/1209732/status_request.zip)
Forgot to add the status request sound file I use :)
